### ISSUE TITLE
r2d2 support for redisgraph

### ISSUE THREAD

**Issue by varunvd** [malte-v/redisgraph-rs#12]
First of all, thank you for the project. Just had a quick question about a contribution.

I have extended the library to accept connections from both r2d2 connection pool and normal existing connection.  Do you prefer to accept the merge request in this repository or should r2d2-redis-graph be a separate repository?

**Comment by malte-v** [comment]
I think a separate crate would be better. That is what most other database clients are doing: https://github.com/sfackler/r2d2#r2d2
