### ISSUE TITLE
Development Plan?

### ISSUE THREAD

**Issue by nb-twy** [malte-v/redisgraph-rs#15]
I am working on a project using redis-rs as my Redis client and came across this library for making it easier to interact with RedisGraph data.  It looks like the last commit was 3 years ago, and the package version is still 0.1.0.  The warning in the README says that it is not fully featured or tested.  I am curious about the following:

1. Has another project made work on redisgraph-rs unnecessary?  If so, will you point me to it please?
2. If you think it would be beneficial to the community to continue work on this project, I would be interested to know what you think it would take to advance it to the next step.
3. Do you have a development plan in mind?  What tests are missing?  What features would you like to see implemented next?  Etc.?

Thank you very much for the work you have already done.

Ciao,
Kurt

**Comment by malte-v** [comment]
hi kurt, thanks for your interest in this project! unfortunately i'm not planning to develop it any further, so if you would like to maintain this thing it would probably be best if you created a fork (i could add a notice to the readme directing people to your fork in that case). regarding your questions:

1. i don't know -- when i created redispraph-rs, there was no comparable library. that may not be the case anymore.

2. & 3. i think the feature that's most urgently needed is a proper query builder (with sanitization of user input etc.) i don't think any concrete tests are missing, the sentence in the readme just means that i haven't used this library in any serious way.

i hope that helped! all the best, malte

**Comment by nb-twy** [comment]
Malte,
Thanks for the quick reply.  I have forked the repo and will spend some time in the code.  I will also do a little more research to see if there is anything else out there under development.  Maybe the redis-rs team would like to absorb the project since that project does not yet have RedisGraph features.  I will check back with you and let you know what I decide to do.

Thanks again!

Ciao,
Kurt
