### ISSUE TITLE
Can't figure out how to get a non-tuple result

### ISSUE THREAD

**Issue by autodidaddict** [malte-v/redisgraph-rs#4]
I'm trying to invoke `query` on the graph so that I can get a non-tuple result because I want to serialize that result across an RPC call so that I can allow my [webassembly modules](https://github.com/wascc) to make calls through the host into this library.

If I can get a stable, serializable type from the results graph, then I can make my webassembly capability provider act like a proxy for this library. My idea was to make my own `ResultSet` type that can build from yours that's got a serde derive on it so I can put it "on the wire".

Is there a special way I can invoke query? It looks like &ResultSet implements FromTable, but I don't know how to call `graph.query` to give me a reference to a ResultSet rather than going right to the tuple extraction.

**Comment by malte-v** [comment]
I've added a `FromTable` implementation for `ResultSet` in https://github.com/malte-v/redisgraph-rs/commit/c9a290c3274663f64c91d05142abb01d63e3736f. Does that resolve your issue?

**Comment by autodidaddict** [comment]
I think so. I also think I figured out how to do it without you needing to add a commit.

- impl `FromTable` in my own struct, which holds a ResultSet internally
- let res: RedisGraphResult<MyTable> = graph.query("...");

**Comment by autodidaddict** [comment]
But your commit saves me the trouble of having to create a type to clone the resultset.

**Comment by malte-v** [comment]
Sure, that's why I added it. It's in 0.3.0 on crates.io.

**Comment by autodidaddict** [comment]
I don't suppose you could add a derive for Seralize and Deserialize on ResultSet? :)

**Comment by malte-v** [comment]
Added in 0.4.0. You're welcome :)

**Comment by autodidaddict** [comment]
You're the best. Thanks!
