### ISSUE TITLE
Question: implementing tuple extractions

### ISSUE THREAD

**Issue by autodidaddict** [malte-v/redisgraph-rs#5]
I've gotten a serialized version of ResultSet from your library, copied it across the wire, and have now re-constituted it inside a wasm module as my own `ResultSet` type with data structures copied from yours (I can't declare a dep inside the wasm module on yours because your module uses `redis`, which has networking libs that don't compile).

What I'm trying to replicate now is the same experience where someone can do:

`let (a: String, b: u32) = my_result_set()` // round-tripped ResultSet

I've got a unit test set up to simulate the right circumstances:

```
fn tuple_extraction_test() {
        let (name, birth_year) : (String, u32) = fake_query("fake query").unwrap();
    }

    fn fake_query<T: FromTable>(query: &str) -> GraphResult<T> {
        query_with_statistics().map(|(value, _)| value)
    }

    fn query_with_statistics<T:FromTable>() -> GraphResult<(T, Statistics)> {
        let result_set = get_result_set()?;
        let value = T::from_table(&result_set)?;
        Ok((value, result_set.statistics))
    }

fn get_result_set() -> GraphResult<ResultSet> {
        Ok(ResultSet{
            statistics: Statistics(vec![]),
            columns: vec![
                Column::Scalars(vec![
                    Scalar::String("tester".to_string()),
                    Scalar::Integer(1985)
                ])
            ]
        })

    }
```

I've got the `impl_row_for_tuple!` macro called in scope, and my test module includes all of the macro invocations from conversions, but I don't know what else I'm missing.. I'm getting the following error in my test:

```
the trait bound `(std::string::String, u32): FromTable` is not satisfied
the trait `FromTable` is not implemented for `(std::string::String, u32)`rustc(E0277)
```

I feel like I've done something really dumb here and I'm just not following how you enabled the tuple extraction stuff. I don't know how else to contact you other than an issue.

Any advice would be much appreciated here. tl;dr I'm trying to replicate the tuple extraction capability on my own private `ResultSet` type and I'm not doing it properly. I'

**Comment by malte-v** [comment]
You can use `from_table(&your_result set)`. The `FromTable` trait needs to be in scope for that.

**Comment by autodidaddict** [comment]
Annnnd sorry I wasted your time. I figured out what I was doing wrong (I hadn't copied enough impls)

**Comment by malte-v** [comment]
You shouldn't need to copy anything or use `impl_row_for_tuple!`. Just do
```rust
use redisgraph::assignments::FromTable;
let (a: String, b: u32) = from_table(&your_result_set);
```

**Comment by malte-v** [comment]
Ah sorry, didn't quite read the issue. Looks like you've figured it out yourself.
